
##
 # startup code provided by Paul Miller for COSC1114 - Operating Systems
 # Principles
 ##

# provide make targets here to build the two programs 

#go into the copier_files filepath and run the make command there
copier: 
	+$(MAKE) -C copier_files

#go into the mtcopier_files filepath and run the make command there
mtcopier:
	+$(MAKE) -C mtcopier_files


#clean by going into each directory and running make clean
clean: 
	cd copier_files && $(MAKE) clean;
	cd mtcopier_files && $(MAKE) clean;




